### PR TITLE
main: fix gopkg.in path handling

### LINKED ISSUE #65: Cannot install gopkg.in/httprequest.v1/cmd/httprequest-generate-client
```
$ gobin gopkg.in/httprequest.v1/cmd/httprequest-generate-client
failed to encode package relative path gopkg.in/httprequest.v1/cmd/httprequest-generate-client: malformed module path "gopkg.in/httprequest.v1/cmd/httprequest-generate-client": invalid version
```

cc @rogpeppe

### PR DESCRIPTION
**Pull request by myitcv**
Also fix a bug whereby the full import path was being used after the
module path for locations within the cache.

Fixes #65.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -306,19 +306,29 @@ func mainerr() error {
...
 
-				epp, err := module.EncodePath(mp.ImportPath)
-				if err != nil {
-					return fmt.Errorf("failed to encode package relative path %v: %v", mp.ImportPath, err)
+				if mp.Module.Path != mp.ImportPath {
+					// We don't need to encode what remains in the pkg path because
+					// we've already uniquely identified the module. If there are
+					// case flips within a module then...  well, we'll see.
+					pkgRem := strings.TrimPrefix(mp.ImportPath, mp.Module.Path+"/")
+					mainrel = filepath.Join(md, filepath.FromSlash(pkgRem))
```
Comment (mvdan) [inline main.go]: shouldn't this be `path`, not `filepath`? since it's a module import path, and not a path of a directory on disk.

Comment (myitcv) [reply main.go]: `filepath` is correct here I think. `md` is the file path of the encoded module path. Hence it only makes sense to join another filepath.
